### ISSUE TITLE
device.provision() never returns a result

### ISSUE THREAD

**Issue by grasmash** [orbital-systems/react-native-esp-idf-provisioning#42]
`const espResponse = await device.provision(ssid, password);` never resolves, whether there is an error or success. It does send the credentials.

**Comment by mateogianolio** [comment]
Hmm do you mean it gets stuck? Could you try the Espressif sample app? Because our code for provisioning:

```swift
self.espDevices[deviceName]!.provision(ssid: ssid, passPhrase: passphrase, completionHandler: { status in
    // Prevent multiple callback invokation error
    guard !invoked else { return }

    switch status {
    case .success:
        resolve([
            "status": "success"
        ])
        invoked = true
    case .failure(let error):
        reject("error", error.description, nil)
        invoked = true
    case .configApplied:
        break
    }
})
```

Is pretty similar to the code called in the ESP sample app for iOS:

https://github.com/espressif/esp-idf-provisioning-ios/blob/master/Example/ESPProvisionSample/ESPProvisionSample/Provision/StatusViewController.swift#L69-L93

**Comment by grasmash** [comment]
Yes, the call gets stuck. Just hangs and doesn’t proceed to the next line.

I can try out the sample app and see if I encounter the same behavior.

**Comment by grasmash** [comment]
Tried the sample app. It hangs at "Confirming Wi-Fi connection" for 10+ minutes with this output:

![image](https://github.com/orbital-systems/react-native-esp-idf-provisioning/assets/539205/5682c313-c5f9-4076-ab6c-21eaae02db34)

**Comment by grasmash** [comment]
Closing as this is an upstream issue.
